name: Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Set up Unity Builder
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2022.3.38f1  # Adjusted to your Unity version

    - name: Build project
      run: |
        mkdir -p Build/WebGLBuild
        # Ensure this matches your Unity build command
        unity -quit -batchmode -nographics -logFile -projectPath . -buildTarget WebGL -executeMethod BuildScript.PerformBuild -buildPath Build/WebGLBuild

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Build/WebGLBuild  # Adjusted to your actual build output directory
        exclude_files: |
          README.md
